//! SeaORM Entity. Generated by sea-orm-codegen 0.5.0

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "loot"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel)]
pub struct Model {
    pub id: i32,
    pub mobid: Option<i32>,
    pub locationid: Option<i32>,
    pub loot_name: String,
    pub description: Option<String>,
    pub preview: Option<Vec<u8>>,
    pub game_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Mobid,
    Locationid,
    LootName,
    Description,
    Preview,
    GameId,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Locations,
    Mobs,
    Games,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::Mobid => ColumnType::Integer.def().null(),
            Self::Locationid => ColumnType::Integer.def().null(),
            Self::LootName => ColumnType::String(None).def(),
            Self::Description => ColumnType::String(None).def().null(),
            Self::Preview => ColumnType::Binary.def().null(),
            Self::GameId => ColumnType::Integer.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Locations => Entity::belongs_to(super::locations::Entity)
                .from(Column::Locationid)
                .to(super::locations::Column::Id)
                .into(),
            Self::Mobs => Entity::belongs_to(super::mobs::Entity)
                .from(Column::Mobid)
                .to(super::mobs::Column::Id)
                .into(),
            Self::Games => Entity::belongs_to(super::games::Entity)
                .from(Column::GameId)
                .to(super::games::Column::Id)
                .into(),
        }
    }
}

impl Related<super::locations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Locations.def()
    }
}

impl Related<super::mobs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Mobs.def()
    }
}

impl Related<super::games::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Games.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
