//! SeaORM Entity. Generated by sea-orm-codegen 0.3.2

pub use super::games::Entity as Games;
pub use super::locations::Entity as Locations;
pub use super::loot::Entity as Loot;
pub use super::mobs::Entity as Mobs;
pub use super::sqlx_migrations::Entity as SqlxMigrations;
