//! SeaORM Entity. Generated by sea-orm-codegen 0.5.0

pub use super::games::Entity as Games;
pub use super::locations::Entity as Locations;
pub use super::loot::Entity as Loot;
pub use super::mobs::Entity as Mobs;
pub use super::users::Entity as Users;
